version: 2.1

orbs:
  node: circleci/node@5.0.2
  browser-tools: circleci/browser-tools@1.4.0
  cypress: cypress-io/cypress@2.1.0
  codecov: codecov/codecov@3.2.3
  jq: circleci/jq@2.2.0

executors:
  cypress:
    docker:
      - image: cypress/base:17.8.0

jobs:
  publish:
    docker:
      - image: cimg/node:16.17.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install node modules
          command: npm install
      - run:
          name: Package library
          command: npm run package:library
      - run:
          name: Update version tag
          command: |
            cd dist/library
            export TAG=$(git describe --tags --abbrev=0)
            contents="$(jq -r --arg tag "$TAG" '.version = $tag' package.json)" && \
            echo "${contents}" > package.json
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/.npmrc
      - run:
          name: Publish library
          command: npm run publish:library

  deploy-demo:
    docker:
      - image: cimg/node:16.17.0
    steps:
      - run:
          name: Trigger Github workflow
          command: |
            curl -H "Accept: application/vnd.github+json" \
              -H "Authorization: token $github_TOKEN" \
              --request POST \
              --data '{"event_type": "deploy"}' \
              https://api.github.com/repos/Cybrid-app/cybrid-sdk-web/dispatches

workflows:
  web-build-and-test:
    jobs:
      - node/test:
          name: test
          version: 16.14.2-browsers
          cache-version: v2
          setup:
            - browser-tools/install-chrome
            - browser-tools/install-chromedriver
            - run:
                command: |
                  google-chrome --version
                  chromedriver --version
                name: Check install
          post-steps:
            - codecov/upload
            - run:
                command: npm run lint
                name: Lint
            - run:
                command: npm audit --audit-level=high
                name: Audit

      - cypress/run:
          name: e2e chromium@101.0.4951.64
          executor: cypress
          post-checkout:
            - run:
                name: Install wget/unzip
                command: |
                  apt update -y
                  apt-get install -y wget
                  apt-get install -y unzip
            - run:
                name: Download/Install Chromium
                command: |
                  wget -O chrome-linux.zip "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F982481%2Fchrome-linux.zip?generation=1647559751806495&alt=media"
                  unzip chrome-linux.zip
          start: npm start
          command: npx cypress run --browser chrome-linux/chrome
          no-workspace: true
          wait-on: http://localhost:4200
          store_artifacts: true

      - cypress/run:
          name: e2e chromium@102.0.5005.61
          executor: cypress
          post-checkout:
            - run:
                name: Install wget/unzip
                command: |
                  apt update -y
                  apt-get install -y wget
                  apt-get install -y unzip
            - run:
                name: Download/Install Chromium
                command: |
                  wget -O chrome-linux.zip "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F992740%2Fchrome-linux.zip?generation=1649975445134595&alt=media"
                  unzip chrome-linux.zip
          start: npm start
          command: npx cypress run --browser chrome-linux/chrome
          no-workspace: true
          wait-on: http://localhost:4200
          store_artifacts: true

      - cypress/run:
          name: e2e chrome@latest
          executor: cypress
          post-checkout:
            - run:
                name: Install libraries
                command: |
                  apt update -y
                  apt install -y software-properties-common apt-transport-https wget fonts-liberation xdg-utils gnupg
            - run:
                name: Download/Install Chrome stable
                command: |
                  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
                  apt update -y
                  dpkg --configure -a
                  dpkg -i google-chrome-stable_current_amd64.deb
          start: npm start
          command: npx cypress run --browser chrome
          no-workspace: true
          wait-on: http://localhost:4200
          store_artifacts: true

      - cypress/run:
          name: e2e edge@latest
          executor: cypress
          post-checkout:
            - run:
                name: Install libraries
                command: |
                  apt update -y
                  apt install -y software-properties-common apt-transport-https wget fonts-liberation xdg-utils gnupg
            - run:
                name: Download/Install Edge stable
                command: |
                  wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | apt-key add -
                  add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
                  apt update -y
                  apt-get -f install -y microsoft-edge-stable
          start: npm start
          command: npx cypress run --browser edge
          no-workspace: true
          wait-on: http://localhost:4200
          store_artifacts: true

      - publish:
          requires:
            - e2e chromium@101.0.4951.64
            - e2e chromium@102.0.5005.61
            - e2e chrome@latest
            - e2e edge@latest
          filters:
            branches:
              only:
                - main

      - deploy-demo:
          requires:
            - publish
          filters:
            branches:
              only:
                - main
